/** Re-export — Hydra typography metrics in [`hydraTypography`](./hydraTypography.ts); antd wiring in [`hydraAntdTypography`](./hydraAntdTypography.ts). */
export {
  hydraAntdTypographyComponentConfig,
  hydraAntdTypographyToken,
} from './hydraAntdTypography';
export {
  brandFontFamily,
  hydraBaseDelete,
  hydraBaseItalic,
  hydraBaseNormal,
  hydraBaseStrong,
  hydraBaseUnderline,
  hydraExtraLargeDelete,
  hydraExtraLargeItalic,
  hydraExtraLargeNormal,
  hydraExtraLargeStrong,
  hydraExtraLargeUnderline,
  hydraFontFamilyName,
  hydraLargeDelete,
  hydraLargeItalic,
  hydraLargeNormal,
  hydraLargeStrong,
  hydraLargeUnderline,
  hydraSmallDelete,
  hydraSmallItalic,
  hydraSmallNormal,
  hydraSmallStrong,
  hydraSmallUnderline,
  hydraTextBaseNormal,
  hydraTextStyleToReactCss,
  hydraTitleHeading1,
  hydraTitleHeading2,
  hydraTitleHeading3,
  hydraTitleHeading4,
  hydraTitleHeading5,
  hydraAntdFontMapFromDesign,
  type HydraTextStyle,
} from './hydraTypography';
